### PR TITLE
feat(docs): Superdesk docs - inital proposal

### PR DESCRIPTION
**Pull request by nidzix**

### CODE REVIEW

**Comment by petrjasek** [comment]
regarding livereload port issues - is the idea to run both `grunt docs` and `grunt server` in parallel?

**Comment by nidzix** [comment]
Yes, that was initial idea, but I'm not sure if that is possible. Maybe we could have `grunt docs` just for running docs, and `grunt docs-dev` for developing with livereload which, then, don't need to go in parallel with `grunt server`

**Comment by petrjasek** [comment]
we can have `grunt docs` for just docs with livereload, or having both docs and server but we would livereload both whenever something would change. so both with just one livereload port and those new watches.
so what about starting with `grunt docs` without server?

**Comment by nidzix** [comment]
I'm not sure I understood your idea :confused:. But I think we need to cover two scenarios.
+ Developers working on `docs` will need to run only this functionality, e.g. `grunt docs-dev`
+ Developers working on `superdesk` will need `grunt server` task, but also need to look in parallel to docs page, from time to time. In this case, how they will access docs: use link under running task, or run another grunt task? 

Is that good point or I am wrong?

**Comment by petrjasek** [comment]
yep that's fine. so there will be:
* `grunt docs` with just docs with livereload,
* `grunt server` with both app and docs
I don't think we need a server without docs.

**Comment by nidzix** [comment]
right, but I don't know how to split `watch` task to have more than one configuration

**Comment by petrjasek** [comment]
just have one config there - no need to split it

**Comment by amagdas** [comment]
:+1: What is the command to generate/view the documentation? `grunt docs`?

**Comment by petrjasek** [comment]
:+1:
@amagdas yes

**Comment by amagdas** [comment]
I think we should update the `README.md` as well.

**Pull request merged**
