### PR TITLE
refactor(workqueue): show items locked by user

### PR DESCRIPTION
**Pull request by petrjasek**
instead of keeping an extra model that requires synchronization

### CODE REVIEW

**Comment by amagdas** [comment]
:+1:  :heart: :blue_heart: :yellow_heart:

**Comment by amagdas** [comment]
:+1:

**Comment by amagdas** [comment]
One possible problem with this approach is that on log-out we unlock all the locked content which will clear the workqueue...

**Comment by petrjasek** [comment]
yep and I think that's a feature not a bug ;)

**Comment by amagdas** [comment]
:smiley: We have to check how this works with session expiry. Cleaning them on user triggered logout should be fine, not sure about automatic session expiry from server.

**Comment by amagdas** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
