### PR TITLE
fix(authoring): Added kicking previous locker of an item out of authorin...

### PR DESCRIPTION
**Pull request by eozan**
...g.

SD-1503

### CODE REVIEW

**Comment by amagdas** [comment]
What is the scenario for this change?

**Comment by eozan** [comment]
When two users are locking/unlocking while the other one is editing (and possibly has unsaved changes), it is inevitable that users will lose data (saving changes over other user's changes which are not displayed to the user who is saving yet). Also in some cases, a user might end up in a state where the item is not locked, screen is not in view mode, but item is not editable.

We wanted to address these situations, and it's decided that locks will not be used in that manner, locking will be a rare occurrence, and we can just close it destructively.

**Comment by eozan** [comment]
Instructions for a scenario can be found here: https://dev.sourcefabric.org/browse/SD-1501

**Comment by petrjasek** [comment]
:ok:

**Comment by amagdas** [comment]
I think this will break read-only mode, will test locally before merging.

**Comment by amagdas** [comment]
Tested and indeed you are kicked out from the article even if you opened it in read-only mode, I don't think that should be the case...

**Comment by eozan** [comment]
I will fix it.

**Comment by amagdas** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
