### PR TITLE
SD-1421 fix Save button state after unlock

### PR DESCRIPTION
**Pull request by amagdas**

### CODE REVIEW

**Comment by amagdas** [comment]
@superdesk/developers Ping!

**Comment by petrjasek** [comment]
looks good :+1: but why is the timeout needed there?

**Comment by amagdas** [comment]
The current digest cycle will flag `$scope.dirty = true` so we need to postpone that code block for the next run.

**Comment by petrjasek** [comment]
ok could be a comment in the source..

**Comment by amagdas** [comment]
Ok, will do.

**Comment by amagdas** [comment]
Updated.

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
