### PR TITLE
multi editing for text items

### PR DESCRIPTION
**Pull request by petrjasek**
you can edit 2-3 items at the same time

### CODE REVIEW

**Comment by amagdas** [comment]
Rebase needed.

**Comment by amagdas** [comment]
Looks good :+1: 
We should probably wait for PO&QA review before merging...

**Comment by nidzix** [comment]
This is good :+1: There are few more commits comming from me soon which will cover all design proposals and complete the request. Should we wait on them or do the merge?

**Comment by amagdas** [comment]
We should wait...
A review before merging would be good.

**Comment by petrjasek** [comment]
@nidzix you can make PR to this branch, it should be fine

**Pull request merged**
