### PR TITLE
[SD-457] : Fix: Pagination should be defaulted each time new filter is a...

### PR DESCRIPTION
**Pull request by sjunaid**
...pplied

### CODE REVIEW

**Comment by petrjasek** [comment]
how does it fix the issue?

**Comment by sjunaid** [comment]
@petrjasek , this initializes the page number (if exist because of previous search), whenever the new filter is applied.(see the reported issue SD-457)

**Comment by petrjasek** [comment]
but how does it know there is a new filter?

**Comment by petrjasek** [comment]
@sjunaid

**Comment by sjunaid** [comment]
@petrjasek , I am modifying it and making a similar type of handling as found in content page(there it's working), please ignore this change and consider next PR for SD-457. thanks

**Comment by petrjasek** [comment]
ok so pls close this PR in case it's obsolete

**Pull request closed without merging**
